spring.application.name=student-management-and-recurring-payments

# ===============================
# Datasource - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/gelo-team-db
spring.datasource.username=gelo_app
spring.datasource.password=Gelo@2026!

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# Server
# ===============================
server.port=8080

