-- Company table
CREATE TABLE companies
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj             VARCHAR(14)  NOT NULL,
    name             VARCHAR(255) NOT NULL,
    cep              VARCHAR(8)   NOT NULL,
    address          VARCHAR(255) NOT NULL,
    city             VARCHAR(100) NOT NULL,
    cellphone_number VARCHAR(20)  NOT NULL,

    CONSTRAINT uq_companies_cnpj UNIQUE (cnpj)
);

-- Integration table
CREATE TABLE integrations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT NOT NULL,
    integration_data TEXT,

    CONSTRAINT fk_integrations_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_integrations_company UNIQUE (company_id)
);

-- Plans table
CREATE TABLE plans
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL,
    name           VARCHAR(255) NOT NULL,
    monthly_amount DOUBLE PRECISION,
    frequency      INTEGER,

    CONSTRAINT fk_plans_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id)
            ON DELETE CASCADE
);

-- User table
CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL,
    name             VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    password         VARCHAR(255) NOT NULL,
    cellphone_number VARCHAR(20),

    CONSTRAINT fk_users_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id)
            ON DELETE CASCADE,

    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Student table
CREATE TABLE students
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT,
    cpf     VARCHAR(11) NOT NULL,
    active  BOOLEAN,

    CONSTRAINT fk_students_plan
        FOREIGN KEY (plan_id)
            REFERENCES plans (id),

    CONSTRAINT uq_students_cpf UNIQUE (cpf)
);

-- Subscriptions table
CREATE TABLE subscriptions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     BIGINT      NOT NULL,
    plan_id        BIGINT      NOT NULL,
    start_date     DATE        NOT NULL,
    status         VARCHAR(20),
    payment_method VARCHAR(30),

    CONSTRAINT fk_subscriptions_student
        FOREIGN KEY (student_id)
            REFERENCES students (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_subscriptions_plan
        FOREIGN KEY (plan_id)
            REFERENCES plans (id)
);

-- Payments table
CREATE TABLE payments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    description     VARCHAR(255),
    value           DOUBLE PRECISION,
    payment_method  VARCHAR(30),
    due_date        DATE,
    issue_date      DATE,
    status          VARCHAR(20),

    CONSTRAINT fk_payments_subscription
        FOREIGN KEY (subscription_id)
            REFERENCES subscriptions (id)
            ON DELETE CASCADE
);