ALTER TABLE students
    ADD COLUMN IF NOT EXISTS birth_date DATE NOT NULL DEFAULT '2000-01-01',
    ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS address VARCHAR(500);
