-- Company table
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(14) NOT NULL,
    name VARCHAR(255) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    cellphone_number VARCHAR(20) NOT NULL,

    CONSTRAINT uq_companies_cnpj UNIQUE (cnpj)
);

-- Plans table
CREATE TABLE plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    monthly_amount DOUBLE PRECISION NOT NULL,
    frequency VARCHAR(100),

    CONSTRAINT fk_plans_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
);

-- User table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    cellphone_number VARCHAR(20),

    CONSTRAINT fk_users_company
        FOREIGN KEY (company_id)
        REFERENCES companies(id)
);

-- Admin table
CREATE TABLE admins (
    id BIGINT PRIMARY KEY,
    CONSTRAINT fk_admins_user
        FOREIGN KEY (id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- Student table
CREATE TABLE students (
    id BIGINT PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL,
    active BOOLEAN,

    CONSTRAINT fk_students_user
        FOREIGN KEY (id)
        REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT uq_students_cpf UNIQUE (cpf)
);

-- Subscriptions table
CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    CONSTRAINT fk_subscriptions_student
        FOREIGN KEY (student_id) REFERENCES students(id),

    CONSTRAINT fk_subscriptions_plan
        FOREIGN KEY (plan_id) REFERENCES plans(id)
);

-- Payments table
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    description VARCHAR(255),
    amount NUMERIC(10,2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    due_date DATE NOT NULL,
    payment_date DATE,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_payments_subscription
            FOREIGN KEY (subscription_id)
            REFERENCES subscriptions(id)
);

-- Indexes